app/main/urls.py
from django.urls import path, re_path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('login/', views.SignIn.as_view(), name="signin"),
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('logout/', views.SignOut.as_view(), name="signout"),
    re_path('search/', views.Search.as_view(), name='search'),
    re_path('storage/(?P<pk>\d+)', views.Storage.as_view(), name="storage"),
    re_path('course/(?P<pk>\d+)', views.CourseDetail.as_view(), name="course"),
    path('favorite/', views.Favorites.as_view(), name="favorites"),
    path('load/', views.FileUpload.as_view(), name="upload"),
    path('all/', views.AllFiles.as_view(), name='all-files'),
    path('add/', views.AddView.as_view(), name='add'),
    path('add_department/', views.AddDepartment.as_view(), name='add-department'),
    path('add_specialization/', views.AddSpecialization.as_view(), name='add-specialization'),
    path('add_course/', views.AddCourse.as_view(), name='add-course'),
    path('add_course_discipline/', views.AddCourseDiscipline.as_view(), name='add-course-discipline'),
    path('add_file_type/', views.AddFileType.as_view(), name='add-file-type'),

    re_path('favorites/remove/(?P<document_id>\d+)/', views.FavoritesRemove.as_view(), name='favorites-remove'),
    re_path('favorites/add/(?P<document_id>\d+)/', views.FavoritesAdd.as_view(), name='favorites-add'),
    re_path('favorites/add-discipline/', views.FavoritesAddDiscipline.as_view(), name='favorites-add-discipline'),
]

app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('app.main.urls', namespace='main')),
]

app/main/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Department(models.Model):
    title = models.CharField('Название', max_length=255)
    image = models.ImageField('Картинка')

    class Meta:
        verbose_name = 'Факультет'
        verbose_name_plural = 'Факультеты'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:storage', args=(self.id,))


class Specialization(models.Model):
    title = models.CharField('Название', max_length=255)
    department = models.ForeignKey(Department, models.CASCADE, verbose_name='Факультет')

    class Meta:
        verbose_name = 'Кафедра'
        verbose_name_plural = 'Кафедра'
        ordering = ('title',)

    def __str__(self):
        return self.title


class Course(models.Model):
    title = models.CharField('Название', max_length=255)
    specialization = models.ForeignKey(Specialization, models.CASCADE, verbose_name='Кафедра')

    class Meta:
        verbose_name = 'Учебная дисциплина'
        verbose_name_plural = 'Учебные дисциплины'
        ordering = ('title',)

    def __str__(self):
        return "{}/{}".format(self.specialization, self.title)


class Type(models.Model):
    title = models.CharField('Название', max_length=255)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Тип файла'
        verbose_name_plural = 'Типы файлов'
        ordering = ('title',)


class CourseDiscipline(models.Model):
    title = models.CharField('Название', max_length=255)
    course = models.ForeignKey(Course, models.CASCADE)

    def __str__(self):
        return str(self.course) + ' - ' + str(self.title)

    class Meta:
        verbose_name = 'Учебный блок'
        verbose_name_plural = 'Учебные блоки'
        ordering = ('course__title', 'title',)


class Document(models.Model):
    title = models.CharField('Название', max_length=255)
    file = models.FileField(verbose_name='Файл')
    type = models.ForeignKey(Type, models.CASCADE, verbose_name='Тип файла')
    author = models.ForeignKey(User, models.CASCADE, verbose_name='Автор')
    course_discipline = models.ForeignKey(CourseDiscipline, models.CASCADE, verbose_name='Предмет', null=True)
    created = models.DateTimeField(verbose_name='Создано', default=timezone.now, editable=False)
    users = models.ManyToManyField(User, related_name='favorites')

    def __str__(self):
        return self.title

    @property
    def course(self):
        if self.course_discipline:
            return self.course_discipline.course
        return None

    @property
    def size(self):
        if self.file:
            return round(self.file.size * 1. / 1000, 1)
        return '-'

    @property
    def extension(self):
        if self.file:
            return self.file.path.split('.')[-1]
        return '-'

    class Meta:
        verbose_name = 'Файл'
        verbose_name_plural = 'Файлы'
        ordering = ('course_discipline__title', 'title',)

templates/add_choice.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <script>
    function show_form(form) {
        $(".collapse").hide();
        $(form).show();
        $('.success').hide();
    }
    </script>
    <body class="bg-white">
    <div class="container">
        <br><br>
        <p>
            <button class="btn btn-outline-primary" type="button" onclick="show_form('#addDepartment')">
                Добавить факультет
            </button>
            <button class="btn btn-outline-primary" type="button" onclick="show_form('#addSpecialization')">
                Добавить кафедру
            </button>
            <button class="btn btn-outline-primary" type="button" onclick="show_form('#addCourse')">
                Добавить учебную дисципину
            </button>
            <button class="btn btn-outline-primary" type="button" onclick="show_form('#addCourseDiscipline')">
                Добавить учебный блок
            </button>
            <button class="btn btn-outline-primary" type="button" onclick="show_form('#addFileType')">
                Добавить тип файла
            </button>
        </p>
        <div class="collapse{% if cform.active %} show{% endif %}" id="addCourse">
            <div class="card card-login mx-auto mt-5">
                <div class="card-header">Добавление Учебной дисциплины</div>
                <div class="card-body">
                    {% with form=cform %}
                        {% include 'inc/form.html' %}
                    {% endwith %}
                </div>
            </div>
        </div>

        <div class="collapse{% if sform.active %} show{% endif %}" id="addSpecialization">
            <div class="card card-login mx-auto mt-5">
                <div class="card-header">Добавление Кафедры</div>
                <div class="card-body">
                    {% with form=sform %}
                        {% include 'inc/form.html' %}
                    {% endwith %}
                </div>
            </div>
        </div>

        <div class="collapse{% if dform.active %} show{% endif %}" id="addDepartment">
            <div class="card card-login mx-auto mt-5">
                <div class="card-header">Добавление Факультета</div>
                <div class="card-body">
                    {% with form=dform %}
                        {% include 'inc/form.html' %}
                    {% endwith %}
                </div>
            </div>
        </div>

        <div class="collapse{% if tform.active %} show{% endif %}" id="addFileType">
            <div class="card card-login mx-auto mt-5">
                <div class="card-header">Добавление Типа файла</div>
                <div class="card-body">
                    {% with form=tform %}
                        {% include 'inc/form.html' %}
                    {% endwith %}
                </div>
            </div>
        </div>

        <div class="collapse{% if cdform.active %} show{% endif %}" id="addCourseDiscipline">
            <div class="card card-login mx-auto mt-5">
                <div class="card-header">Добавление Учебного блока</div>
                <div class="card-body">
                    {% with form=cdform %}
                        {% include 'inc/form.html' %}
                    {% endwith %}
                </div>
            </div>
        </div>
    </div>
    <script>
        $("input.form-control").val("");
    </script>
    </body>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="/static/js/jquery.js" ></script>
    <script src="/static/js/main.js" ></script>
</head>
<body>

    <nav class="navbar navbar-expand navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'main:index' %}">База учебных материалов МГТУ им.Баумана</a>
        {% if request.user.is_authenticated %}
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Главная <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:all-files' %}">Все файлы <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:favorites' %}">Избранное <span class="sr-only">(current)</span></a>
                </li>
                {% if request.user.groups.first.name == 'Преподаватели' %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:upload' %}">Загрузить файл <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:add' %}">Добавить раздел<span class="sr-only">(current)</span></a>
                </li>
                {% endif %}
            </ul>
        </div>
        <ul class="navbar-nav mr-sm-2 position-absolute" style="right: 0">
            <li class="nav-item">
                <a class="nav-link active">{{ request.user.get_full_name }}, <i>{{ request.user.groups.first }}</i><span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:signout' %}">Выход<span class="sr-only">(current)</span></a>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav mr-sm-2 position-absolute" style="right: 0">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:signin' %}">Авторизация<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:signup' %}">Регистрация<span class="sr-only">(current)</span></a>
            </li>
        </ul>
        {% endif %}
    </nav>

    {% block content %}
    {% endblock %}


</body>
</html>

templates/favorites.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="container">
        <div class="row">
        {% if object_list %}
            {% for object in object_list %}
                {% include 'inc/document.html' %}
            {% endfor %}
        {% else %}
            <div class="col-12"><br />
                <h4>Вы ещё не делали закладок.</h4>
            </div>
        {% endif %}
        </div>
    </div>
    <script>$('.favorites-remove').on('click', remove_from_favorites);</script>

{% endblock %}

templates/files.html
{% extends "base.html" %}
{% load staticfiles app_extra %}
{% block content %}

    <div class="container bott">
        <div class="row">
            <div class="col-12">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item">{{ object.specialization.department }}</li>
                    <li class="breadcrumb-item">{{ object.specialization }}</li>
                    <li class="breadcrumb-item">{{ object.title }}</li>
                </ul>
            </div>
        </div>
    </div>

    {% type_choice %}

    <div class="container">
        <br>
        <div class="row">
        {% if document_list %}
            {% for object in document_list %}
                {% include 'inc/document.html' %}
            {% endfor %}
        {% else %}
            <div class="col-12">
                <h4>К сожалению здесь ещё нет материалов. Попробуйте просмотреть другой предмет.</h4>
            </div>
        {% endif %}
        </div>

    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <body>

        {% include 'inc/search.html' %}
        <!-- Карточка предмета -->
        <div class="container">
            <div class="row">
                {% for object in object_list %}
                    {% include 'inc/card_with_pic.html' %}
                {% endfor %}
            </div>
        </div>
    </body>
{% endblock %}

templates/load.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}


<body class="bg-white">
  <div class="container">
    <div class="card card-login mx-auto mt-5">
      <div class="card-header">Загрузка файла</div>
      <div class="card-body">
        <form action="{% url 'main:upload' %}" method="post" enctype="multipart/form-data">
            {{ form.non_field_errors }}
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    <label class="control-label col-xs-3" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                </div>
            {% endfor %}
          <button type="submit" class="btn btn-primary btn-block">Загрузить</button>
        </form>
      </div>
    </div>
  </div>
  {% if success %}
    <div class="container bott">
        <div class="row">
            <div class="col-12">
                <h4>Файл успешно загружен загружен.</h4>
            </div>
        </div>
    </div>
  {% endif %}
    <script>
        $("input.form-control").val("");
    </script>
</body>

{% endblock %}

templates/search.html
{% extends "base.html" %}
{% load staticfiles app_extra %}
{% block content %}

    {% include 'inc/search.html' %}
    {% type_choice %}

    <div class="container bott">
        <div class="row">
        {% if object_list %}
            {% if query %}
            <div class="col-12">
                <h4>Результаты поиска по разпросу "{{ query }}":</h4>
            </div>
            {% endif %}
            {% for object in object_list %}
                {% include 'inc/document.html' %}
            {% endfor %}
        {% elif query == '' %}
            <div class="col-12">
                <h4>К сожалению, задан пустой поисковый запрос. Попробуйте снова.</h4>
            </div>
        {% else %}
            <div class="col-12">
                <h4>К сожалению,{% if query %} по запроcу "{{ query }}"{% endif %} ничего не найдено. Попробуйте снова.</h4>
            </div>
        {% endif %}
        </div>
    </div>

    <div class="container bott">
        <div class="row">
        </div>
    </div>
{% endblock %}

templates/storage.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
    <style>
    .button-container {
        display: none;
    }
    </style>
    <script>
    var active_course;
    function select_specialization(o, _id) {
        $('.specialization').removeClass('active');
        $(o).addClass('active');
        $('.courses').hide();
        $('#spec_' + _id).show();
        console.log($(o).children('.card'));
        if ($('#spec_' + _id).children('.card').length == 0) {
            $('.button-container').hide();
        }
        active_course = null;
    }
    function activate_course(o, _id) {
        $('.course').removeClass('active');
        $(o).addClass('active');
        $('.button-container').show();
        active_course = _id;
    }
    function go_to_documents() {
        if (active_course) {
            document.location.replace('/course/' + active_course + '/')
        }
    }
    </script>
    <div class="container">
        <br>
        <div class="row">
            {% if specialization_list %}
            <div class="col-6 facultet">
				<div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Кафедра</h5>
                    </div>
                    <div>
                        {% for object in specialization_list %}
                        <ul class="list-group" >
                            <li class="specialization list-group-item" onclick="select_specialization(this, {{ object.id }})">{{ object }}</li>
                        </ul>
                        {% endfor %}
					</div>
				</div>
			</div>
            {% for specialition in specialization_list %}
            <div class="col-6 facultet courses" id="spec_{{ specialition.id }}" style="display: none;">
                {% if specialition.course_set.exists %}
				<div class="card">
                    <div class="card-header">
                        <h5 class="card-title">Учебная дисциплина</h5>
                    </div>
                    {% for course in specialition.course_set.all %}
					<div>
                        <ul class="list-group">
                            <li class="list-group-item course" onclick="activate_course(this, {{ course.id }})">{{ course.title }}</li>
                        </ul>
					</div>
                    {% endfor %}
				</div>
                {% else %}
                <h4>К сожалению, данный раздел еще не наполнен</h4>
                {% endif %}
			</div>
            {% endfor %}
            {% else %}
                <h4>К сожалению, данный раздел еще не наполнен</h4>
            {% endif %}
        </div>
    </div>



    {% if specialization_list %}
    <div class="container button-container">
        <div class="row">
            <div class="col-12">
                <a class="btn btn-primary" href="#" onclick="go_to_documents()" role="button">Перейти</a>
            </div>
        </div>
    </div>
    {% endif %}

{% endblock %}