app/main/urls.py
from django.urls import path, re_path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('login/', views.SignIn.as_view(), name="signin"),
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('logout/', views.SignOut.as_view(), name="signout"),
    re_path('search/', views.Search.as_view(), name='search'),
    re_path('storage/(?P<pk>\d+)', views.Storage.as_view(), name="storage"),
    re_path('course/(?P<pk>\d+)', views.CourseDetail.as_view(), name="course"),
    path('favorite/', views.Favorites.as_view(), name="favorites"),
    path('load/', views.FileUpload.as_view(), name="upload"),
    path('all/', views.AllFiles.as_view(), name='all-files'),
    path('add/', views.AddView.as_view(), name='add'),
    path('add_department/', views.AddDepartment.as_view(), name='add-department'),
    path('add_specialization/', views.AddSpecialization.as_view(), name='add-specialization'),
    path('add_course/', views.AddCourse.as_view(), name='add-course'),
    path('add_course_discipline/', views.AddCourseDiscipline.as_view(), name='add-course-discipline'),
    path('add_file_type/', views.AddFileType.as_view(), name='add-file-type'),

    re_path('favorites/remove/(?P<document_id>\d+)/', views.FavoritesRemove.as_view(), name='favorites-remove'),
    re_path('favorites/add/(?P<document_id>\d+)/', views.FavoritesAdd.as_view(), name='favorites-add'),
    re_path('favorites/add-discipline/', views.FavoritesAddDiscipline.as_view(), name='favorites-add-discipline'),
]

app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('app.main.urls', namespace='main')),
]

templates/inc/card_with_pic.html
<div class="col-3 facultet">
    <div class="card text-white">
        <img class="card-img" src="{{ object.image.url }}" alt="Card image cap">
        <div class="card-img-overlay">
            <a href="{{ object.get_absolute_url }}"><h5 class="card-title">{{ object.title }}</h5></a>
        </div>
    </div>
</div>

templates/inc/document.html
<div class="col-3 facultet">
    <div class="card">
        <div class="card-header">
            <h6 class="document-title">{{ object.title }}</h6>
        </div>
        <div class="card-body disc{{ object.course_discipline.id }}">
            <p class="card-text">{{ object.course_discipline }}</p>
            <p>Тип Файла: {{ object.type.title }}</p>
            <p>Размер: {{ object.size }} КБ</p>
            <p>Расширение: {{ object.extension }}</p>
            <p>Источник: {{ object.author.get_full_name }}</p>
            <p>Дата добавления:&nbsp;{{ object.created|date:"SHORT_DATE_FORMAT" }}</p>
            <a class="btn btn-outline-danger favorites-remove"{% if object not in request.user.favorites.all %} style="display: none"{% endif %} onclick="$.get('{% url 'main:favorites-remove' object.id %}'); toggle_favorite(this);">Удалить из &star;</a>
            <a class="btn btn-outline-warning favorites-add"{% if object in request.user.favorites.all %} style="display: none"{% endif %} onclick="$.get('{% url 'main:favorites-add' object.id %}'); toggle_favorite(this);">Добавить в &star;</a>
            <br><br>
            <a href="{{ object.file.url }}" class="btn btn-outline-primary" download>Скачать</a>
        </div>
    </div>
</div>

templates/inc/filter.html
<div class="container input-group search">
    <form action="{{ request.get_full_path }}" id="typeChoiceForm" method="get">
        <div style="display: inline-block">
        <label class="control-label col-xs-3" for="typeChoice">Тип файла</label>
        <select name="typeFilter" class="custom-select" id="typeChoice">
            <option value="">Любой тип</option>
            {% for type in type_choices %}
            <option value="{{ type.id }}"{% if current == type.id %} selected{% endif %}>{{ type.title }}</option>
            {% endfor %}
        </select>
        </div>
        {% if block_choices %}
        <div style="display: inline-block">
        <label class="control-label col-xs-3" for="blockChoice">Учебный блок</label>
        <select name="blockFilter" class="custom-select" id="blockChoice">
            <option value="">Любой тип</option>
            {% for type in block_choices %}
            <option value="{{ type.id }}"{% if current_block == type.id %} selected{% endif %}>{{ type.title }}</option>
            {% endfor %}
        </select>
        </div>
        <div style="display: inline-block">
        <a class="btn btn-outline-warning favorites-add" onclick="$.get('{% url 'main:favorites-add-discipline' %}?disc_id=' + $('#blockChoice').val()); $('.disc' + $('#blockChoice').val()).map(updateEl)">Добавить блок в &star; </a>
        </div>

        {% endif %}
    </form>
</div>
<script>
  var addParam = function( url, key, value )
  {
    var url = new URL(url);

    // If your expected result is "http://foo.bar/?x=42&y=2"
    url.searchParams.set(key, value);

    return url.href;
  };

  $("#typeChoice").change(function(){
      window.location.href = addParam(window.location.href, 'typeFilter', $("#typeChoice").val())
  });
  $("#blockChoice").change(function(){
      window.location.href = addParam(window.location.href, 'blockFilter', $("#blockChoice").val())
  });

  var updateEl = function (i, parent) {
      parent = $(parent);
    var addEl = parent.children('.favorites-add');
    var removeEl = parent.children('.favorites-remove');
    addEl.hide();
    removeEl.show();
  }
</script>

templates/inc/form.html
<form action="{% url form.Meta.action %}" method="post" enctype="multipart/form-data">
    {{ form.non_field_errors }}
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
            {{ field.errors }}
            <label class="control-label col-xs-3" for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary btn-block">Добавить</button>
</form>
{% if form.active %}
<div class="row success">
    <div class="col-12">
        <h4>{{ form.Meta.success_action_text }}</h4>
    </div>
</div>
{% endif %}

templates/inc/search.html
<form action="{% url 'main:search' %}" method="get">
    <div class="container input-group search">
        <input type="text" class="form-control" placeholder="Введите название файла" aria-label="Введите название файла" aria-describedby="basic-addon2" name="q">
        <div class="input-group-append">
            <button class="btn btn-outline-primary" type="submit">Искать</button>
        </div>
    </div>
</form>